name: WDIO Test

on:
  push

jobs:
  test-runner:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        run: ["g4m"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update All Packages
        run: sudo apt-get update -y

      - name: Download Chrome browser
        run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

      - name: Install Chrome browser
        run: sudo dpkg -i google-chrome-stable_current_amd64.deb

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: NPM Install
        run: npm install

      - name: Install specific version of Chromedriver for GH
        run: npm install chromedriver@${{ vars.CHROME_VERSION }}

      - name: Run Test - ${{ matrix.run }}
        id: testing
        run: npm test
        env:
          VARIABLE: ${{ steps.testing.outputs.variable }}

      - name: Set job report variables
        id: test-results
        if: ${{ always() }}
        run: |
          echo "JOB_STATUS=${{ job.status }}" >> $GITHUB_ENV
          sed -i "s/\$JOB_STATUS/${{ job.status }}/g" ".github/workflows/slack-messaging/slack-payload-${{ matrix.run }}-${{ job.status }}.json"

          echo "URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV
          sed -i "s/\$URL/${{ env.URL }}/g" ".github/workflows/slack-messaging/slack-payload-${{ matrix.run }}-${{ job.status }}.json"

          echo "MATRIX_RUN=${{ matrix.run }}" >> $GITHUB_ENV

      - name: Print test output
        if: ${{ always() }}
        run: echo "Test Output= ${{ env.TEST_OUTPUT }}"


      - name: Notify on Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C058GP7SQA0"
          payload-file-path: ".github/workflows/slack-messaging/slack-payload-${{ matrix.run }}-${{ job.status }}.json"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.WDIO_SLACKBOT_TOKEN }}
