name: WDIO Test

on:
  push
env:
  PASSED: 0
  FAILED: 0  
jobs:
  test-runner:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        run: ["g4m", "av"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update All Packages
        run: sudo apt-get update -y

      - name: Download Chrome browser
        run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

      - name: Install Chrome browser
        run: sudo dpkg -i google-chrome-stable_current_amd64.deb

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: NPM Install
        run: npm install

      - name: Install specific version of Chromedriver for GH
        run: npm install chromedriver@${{ vars.CHROME_VERSION }}

      - name: Run Test - ${{ matrix.run }}
        run: npm test

      - name: Upload passed variable
        uses: actions/upload-artifact@v2
        with:
          name: passed
          path: passed.txt

      - name: Upload failed variable
        uses: actions/upload-artifact@v2
        with:
          name: failed
          path: failed.txt

      - name: Download passed variable
        uses: actions/download-artifact@v2
        with:
          name: passed
          path: .

      - name: Download failed variable
        uses: actions/download-artifact@v2
        with:
          name: failed
          path: .

      - name: Use passed variable
        run: |
         value=$(cat passed.txt)
         echo "Updated value: $value"

      - name: Use failed variable
        run: |
         value=$(cat failed.txt)
         echo "Updated value: $value"

      - name: Set job report variables
        if: ${{ always() }}
        run: |
          echo "JOB_STATUS=${{ job.status }}" >> $GITHUB_ENV
          sed -i "s/\$JOB_STATUS/${{ job.status }}/g" ".github/workflows/slack-messaging/slack-payload-${{ matrix.run }}-${{ job.status }}.json"

          echo "URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV
          sed -i "s/\$URL/${{ env.URL }}/g" ".github/workflows/slack-messaging/slack-payload-${{ matrix.run }}-${{ job.status }}.json"

          echo "MATRIX_RUN=${{ matrix.run }}" >> $GITHUB_ENV

