name: WDIO Test

on:
  workflow_dispatch:
 
  
jobs:
  send-slack-message:
    runs-on: ubuntu-latest
    steps:
      - name: Get Slack user ID
        id: slack-user-id
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          response=$(curl -s -X POST -H "Authorization: Bearer $SLACK_TOKEN" \
            -H "Content-type: application/json" \
            -d '{
              "email": "jamie.pollard@gear4music.com"  // email address of the user who started the workflow
            }' \
            https://slack.com/api/users.lookupByEmail)
          echo "::set-output name=user_id::$(echo $response | jq -r '.user.id')"
          echo "Slack User ID: $user_id"
          echo "::set-output name=user_id::$user_id"
      
      - name: Send Slack message
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          USER_ID: ${{ steps.slack-user-id.outputs.user_id }}
        run: |
          curl -X POST -H "Authorization: Bearer $SLACK_TOKEN" \
            -H "Content-type: application/json" \
            -d '{
              "channel": "$USER_ID",
              "text": "Your workflow has started!"
            }' \
            https://slack.com/api/chat.postMessage

