name: Slack messaging test

on:
  workflow_dispatch:
 
  
jobs:
  send-slack-message:
    runs-on: ubuntu-latest
    steps:
      - name: Get Slack user ID
        id: slack-user-id
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          response=$(curl -s -X POST -H "Authorization: Bearer $SLACK_TOKEN" \
            -H "Content-type: application/json" \
            -d '{
              "email": "user@example.com"  // Replace with the email address of the user who started the workflow
            }' \
            https://slack.com/api/users.lookupByEmail)
          echo "Slack API Response: $response"
          user_id=$(echo $response | jq -r '.user.id')
          echo "Slack User ID: $user_id"
          echo "::set-output name=user_id::$user_id"

